############################
# Last Update: 01/07/2026
# Contact: www.github.com/syahir-37/vprofile.git
############################

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  # Disable Guest plugin:
  # un# the command if vagrant asking about update VM kernel:
  #config.vbguest.auto_update = false

  ### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "bento/rockylinux-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    # Reference external script file
    db01.vm.provision "shell", path: "mysql.sh"
    end
  end


  ### Memcache vm  ####
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "bento/rockylinux-9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    # Reference external script file
    mc01.vm.provision "shell", path: "memcache.sh"
    end
  end


  ### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "bento/rockylinux-9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.13"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    # Reference external script file
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
    end
  end


  ### tomcat vm ####
  config.vm.define "app01" do |app01|
    app01.vm.box = "bento/rockylinux-9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "800"
    # Reference external script file
    app01.vm.provision "shell", path: "tomcat.sh"
    end
  end


  ### Nginx VM ####
  config.vm.define "web01" do |web01|
    web01.vm.box = "bento/ubuntu-24.04"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "800"
    # Reference external script file
    web01.vm.provision "shell", path: "nginx.sh"
    end
  end

end
